### ISSUE TITLE
No EMS yet for host with extracted host ID:

### ISSUE THREAD

**Issue by mosiuoat** [openbaton/openimscore-packages#4]
Hi, so I am able to launch the NSD and deploy nodes from a template image. All is up incl floating IPs except for the services themselves. I get the error message "No EMS yet for host with extracted ID: ". 

The logs show the following (repeated for all VNFs):

2017-03-31 10:26:14.416  INFO 14 --- [SimpleAsyncTaskExecutor-3] org.openbaton.nfvo.vnfm_reg.VnfmManager  : Executing Task errorTask for vnfr fhoss. Cyclic=true
2017-03-31 10:26:14.416 ERROR 14 --- [OpenbatonTask-13] o.o.n.v.tasks.abstracts.AbstractTask     : ERROR from VNFM: java.lang.RuntimeException: No EMS yet for host with extracted host ID: 1219752
2017-03-31 10:26:14.426 ERROR 14 --- [OpenbatonTask-13] o.o.n.v.tasks.abstracts.AbstractTask     : Received ERROR message from VNFM related to VNFR: fhoss
2017-03-31 10:26:17.880  INFO 14 --- [SimpleAsyncTaskExecutor-2] org.openbaton.nfvo.vnfm_reg.VnfmManager  : Executing Task errorTask for vnfr bind9. Cyclic=true
2017-03-31 10:26:17.880 ERROR 14 --- [OpenbatonTask-12] o.o.n.v.tasks.abstracts.AbstractTask     : ERROR from VNFM: java.lang.RuntimeException: No EMS yet for host with extracted host ID: 9864777
2017-03-31 10:26:17.889 ERROR 14 --- [OpenbatonTask-12] o.o.n.v.tasks.abstracts.AbstractTask     : Received ERROR message from VNFM related to VNFR: bind9

My environment:
- NFVO 3.2.0
- Vim Driver 3.2.3-SNAPSHOT
- Openstack Newton

Mos

**Comment by gc4rella** [comment]
It maybe due to a wrong configuration of the NFVO/generic vnfm. Could you please share the properties files?

**Comment by mosiuoat** [comment]
Hi,

The properties files in /etc/openbaton (attached) remain changed from the running of the Docker container. 

The generic NFVO log file contains repeated lines as follows:

2017-03-31 10:26:05.126 DEBUG 10 --- [SimpleAsyncTaskExecutor-5] o.o.v.g.core.ElementManagementSystem     : Number of expected EMS hostnames: 5
2017-03-31 10:26:05.126 DEBUG 10 --- [SimpleAsyncTaskExecutor-5] o.o.v.g.core.ElementManagementSystem     : Waiting for icscf-3714293 EMS to be started... (245 secs)
2017-03-31 10:26:05.126 DEBUG 10 --- [SimpleAsyncTaskExecutor-5] o.o.v.g.core.ElementManagementSystem     : Expected hostnames: [pcscf-6795019, scscf-2487355, bind9-9864777, icscf-3714293, fhoss-1219752]
2017-03-31 10:26:05.127 ERROR 10 --- [SimpleAsyncTaskExecutor-5] o.o.common.vnfm_sdk.AbstractVnfm         : ERROR:

java.lang.RuntimeException: No EMS yet for host with extracted host ID: 3714293
        at org.openbaton.vnfm.generic.core.ElementManagementSystem.checkEmsStarted(ElementManagementSystem.java:165)
        at org.openbaton.vnfm.generic.core.ElementManagementSystem.checkEms(ElementManagementSystem.java:126)
        at org.openbaton.vnfm.generic.GenericVNFM.instantiate(GenericVNFM.java:88)
        at org.openbaton.common.vnfm_sdk.AbstractVnfm.onAction(AbstractVnfm.java:361)
        at org.openbaton.common.vnfm_sdk.amqp.AbstractVnfmSpringAmqp.onAction(AbstractVnfmSpringAmqp.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
        at org.springframework.amqp.rabbit.listener.adapter.MessageListenerAdapter.invokeListenerMethod(MessageListenerAdapter.java:327)
        at org.springframework.amqp.rabbit.listener.adapter.MessageListenerAdapter.onMessage(MessageListenerAdapter.java:253)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:756)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:679)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$001(SimpleMessageListenerContainer.java:83)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$1.invokeListener(SimpleMessageListenerContainer.java:170)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.invokeListener(SimpleMessageListenerContainer.java:1257)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:660)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:1021)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:1005)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$700(SimpleMessageListenerContainer.java:83)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1119)
        at java.lang.Thread.run(Thread.java:745)

[openbaton-nfvo.txt](https://github.com/openbaton/openimscore-packages/files/885841/openbaton-nfvo.txt)

[openbaton-vnfm-generic.txt](https://github.com/openbaton/openimscore-packages/files/885842/openbaton-vnfm-generic.txt)

Mos

**Comment by mosiuoat** [comment]
Sorry you can close this ticket, the underlying problem was something wrong with cinder, thanks

**Comment by joSchnee** [comment]
hello, I'm facing with the same problem. How do you solve it?

**Comment by lorenzotomasini** [comment]
Hi @joSchnee,

Can you please check if the nfvo.broker.ip is correctly set in the openbaton-nfvo.properties? if so whenever the VM deployed is able to reach this ip at the port 5672?

if you can, share with us the nfvo, genericvnfm and VM (/var/log/cloud-init-output and /var/log/openbaton/*) log files

**Comment by joSchnee** [comment]
Hi lorenzotomasini,
Yes, I did not change the nfvo.broker.ip from "localhost" to its real ip.  It works fine now, Thanks a lot!
BR,
Jo

**Comment by joSchnee** [comment]
Hi @lorenzotomasini ,

I'm using Debian image in my NSD, and got the same error  "No EMS yet for host". I've checked the user-data.sh of generic-vnfm, found that it only defines the ems installation on Ubuntu and Centos. So I'm writing to ask, if there is any solution for Debian image. 

BR,
jo

**Comment by lorenzotomasini** [comment]
Hi @joSchnee 

At the moment only CentOS and Ubuntu are the supported OS of the EMS. We are currently working to integrate Debian in the next release thanks to your comment. The change should be very easy (probably only a matter of if conditions) in the user-data provided by the Generic VNFM [here](https://github.com/openbaton/generic-vnfm/blob/master/src/main/resources/user-data.sh). If you don't want to wait, you can fix it yourself (and provide then a pull request 😃 ). If you have used the bootstrap for installing debian packages, this file should be under the /etc/openbaton folder

thanks
Lorenzo
